name: Deploy to AWS S3
on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: NodeJs Setup
        uses: actions/setup-node@v1
        with:
          node-version: ${{ secrets.node_version }}

      - name: Dependency Install
        run: npm install

      - name: Build App
        run: npm run build
        env: 
          VITE_RESUME_URL: ${{ secrets.VITE_RESUME_URL }}

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}      
          aws-region: ap-south-1

      - name: Deploy to AWS S3
        run: aws s3 sync dist s3://portfolio-zeeshan --delete

      - name: Create Cloudfront Invalidation
        uses: josemando/aws-cloudfront-create-invalidation@v1
        with: 
          distribution-id: ES3CMTRSI36YA
          paths: /*
